name: Sync Posts to Master

on:
  push:
    branches:
      - _posts

jobs:
  sync-posts:
    name: Sync Posts
    runs-on: ubuntu-latest

    steps:
      - name: Create directory for _posts branch
        run: |
          mkdir -p _posts-dir

      - name: Create directory for master branch
        run: |
          mkdir -p master-dir

      - name: Checkout _posts branch
        uses: actions/checkout@v4.1.1
        with:
          ref: _posts
          path: _posts-dir

      - name: Checkout master branch
        uses: actions/checkout@v4.1.1
        with:
          ref: master
          path: master-dir

      - name: Sync posts to source/_posts
        run: |

          rm -rf master-dir/source/_posts/*
          cp -r _posts-dir/* master-dir/source/_posts/
          cd master-dir/

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add source/_posts/
          git commit -m "Sync posts from _posts branch"
          git push origin master

        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
