name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Copy files
    runs-on: ubuntu-22.04 # rsync --mkpath 在 ubuntu-22.04 才有这个参数

    steps:
      # 检出 Git 仓库
      - name: Checkout repository
        uses: actions/checkout@v3

      # 安装 jq 工具
      - name: Install jq
        run: sudo apt-get install jq

      # 构建，根据 map.json 拷贝文件，路径都是都对项目根目录的路径
      - name: Copy files to directory public
        run: |

          # 启用错误处理
          set -e

          # 处理 rsync 错误
          function handle_error 
          {
            echo "Rsync failed with exit code $1."
            exit 1
          }

          # 执行 rsync 命令
          cat .github/workflows/map.json | jq -r 'to_entries[] | "rsync --mkpath \(.key) \(.value)"' | while read -r command; do
            echo "Executing: $command"
            eval "$command"
            if [ $? -ne 0 ]; then
              handle_error $?
            fi
          done

          echo "Files copied successfully."

      # 上传构建产物
      - name: Upload artifacts
        # 链接 https://github.com/actions/upload-artifact/
        uses: actions/upload-artifact@v4.3.0
        with:
          name: _posts
          path: public

  deploy-posts:
    name: Deploy to _posts
    runs-on: ubuntu-latest
    needs: build  # 表示依赖于 build 作业完成
    steps:
      - name: Download artifact
        # 链接 https://github.com/actions/download-artifact
        uses: actions/download-artifact@v4.0.0
        with:
          name: _posts
          path: dists

      - name: Deploy to gh-pages-deprecated
        # 链接 https://github.com/crazy-max/ghaction-github-pages/
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          repo: DavidingPlus/blog # 部署到 blog 项目
          target_branch: _posts
          build_dir: dists
          keep_history: false # 开启以后虽然会有 git 历史，但是无法在部署分支自动清理本该删除的文件，个人觉得不舒服，所以关了。
          allow_empty_commit: false
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }} 
